# Generated by Django 5.2.3 on 2025-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.CharField(default="", max_length=100),
        ),
    ]
