# Generated by Django 5.2.3 on 2025-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="곡일련번호"
                    ),
                ),
                ("rank", models.IntegerField(verbose_name="순위")),
                ("album", models.CharField(max_length=200, verbose_name="앨범")),
                ("title", models.CharField(max_length=200, verbose_name="곡명")),
                ("artist", models.CharField(max_length=200, verbose_name="가수")),
                (
                    "cover_image_url",
                    models.URLField(max_length=500, verbose_name="커버이미지 주소"),
                ),
                ("lyrics", models.TextField(verbose_name="가사")),
                ("genre", models.CharField(max_length=100, verbose_name="장르")),
                ("release_date", models.DateField(verbose_name="발매일")),
                ("likes", models.IntegerField(verbose_name="좋아요")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "노래",
                "verbose_name_plural": "노래들",
                "ordering": ["rank"],
            },
        ),
    ]
